version: '3.8'
services:
  example_db:
    image: mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: example_db
      MYSQL_USER: example_db_user
      MYSQL_PASSWORD: example_db_user_password
    ports:
      - "3306:3306"
    networks:
      - example_network
  example_app:
    build:
      context: ./
    ports:
      - "8080:8080"
    networks:
      - example_network
    depends_on:
      - example_db
networks:
  example_network:
    driver: bridge
